# Generated by Django 4.2.5 on 2023-09-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='Product_name',
        ),
    ]
