# Generated by Django 4.2.5 on 2023-09-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0002_rename_product_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='product_name',
        ),
    ]
