# Generated by Django 4.2.5 on 2023-09-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0003_rename_product_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategoru',
            new_name='subcategory',
        ),
    ]
